// <auto-generated />
using System;
using ControleEstacionamento.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleEstacionamento.Migrations
{
    [DbContext(typeof(ControleEstacionamentoContext))]
    [Migration("20240914193834_TabelaValores")]
    partial class TabelaValores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleEstacionamento.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFimVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("valores");
                });

            modelBuilder.Entity("ControleEstacionamento.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<DateTime>("HorarioChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.Property<int>("ValorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValorId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("ControleEstacionamento.Models.Veiculo", b =>
                {
                    b.HasOne("ControleEstacionamento.Models.Valor", "Valor")
                        .WithMany()
                        .HasForeignKey("ValorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Valor");
                });
#pragma warning restore 612, 618
        }
    }
}
